# Тема 10. Декораторы и исключения
Отчет по Теме #10 выполнил(а):
- Свинцова Софья Александровна
- ПИЭ-22-1

| Задание    | Лаб_раб | Сам_раб |
|------------|---------|---------|
| Задание 1  | +       | +       |
| Задание 2  | +       | +       |
| Задание 3  | +       | +       |
| Задание 4  | +       | +       |
| Задание 5  | +       | +       |

знак "+" - задание выполнено; знак "-" - задание не выполнено;

Работу проверили:
- к.э.н., доцент Панов М.А.

## Лабораторная работа №10
#1.

```python
from functools import lru_cache


@lru_cache(None)
def fibonacci(n):
    if n == 0:
        return 0
    elif n == 1:
        return 1
    return fibonacci(n - 1) + fibonacci(n - 2)

print(fibonacci(100))
```
### Результат.

![Меню](https://github.com/ssselfish/SoftwareEngineering/blob/Тема_10/лаб10/1.png)

### Вывод
рекурсивная функция для подсчета чисел fibonacci с инструментом lru_cash

#2. 

```python
def check(input_func):
    def output_func(*args):
        name, age = args[0], args[1]

        if age < 0 or age > 130:
            age = 'Недопустимый возраст'
        input_func(name, age)

    return output_func


@check
def personal_info(name, age):
    print(f"Name: {name} Age: {age}")

personal_info('Владимир', 38)
personal_info('Александр', -5)
personal_info('Петр', 138, 15, 48, 2)
```
### Результат.

![Меню](https://github.com/ssselfish/SoftwareEngineering/blob/Тема_10/лаб10/2.png)

### Вывод
проверка на возраст с помощью декоратора

#3.

```python
def data(*args):
    try:
        for i in range(len(*args)):
            try:
                result = (args[0][i] * 15) // 10
                print(result)
            except Exception as ex:
                print(ex)
    except Exception as ex:
        print(ex)
    finally:
        print('Вся информация обработана')
if __name__ == '__main__':
     data([1, 15, 'Hello', 'i', 'try', 'to', 'crash', 'your', 'site', 38, 45])
```
### Результат.

![Меню](https://github.com/ssselfish/SoftwareEngineering/blob/Тема_10/лаб10/3.png)

### Вывод
функция, которая обернута в try и except

#4.

```python
class NegativeValueException(Exception):
    pass

def check_name(name):
    if len(name) > 10:
        raise NegativeValueException('Длина более 10 символов')
    else:
        print('Успешная регистрация')

if __name__ == '__main__':
    name = '123456788910'
    check_name(name)
```
### Результат.

![Меню](https://github.com/ssselfish/SoftwareEngineering/blob/Тема_10/лаб10/4.png)

### Вывод
проверка name на длину с помощью exception

#5. 
```python
class SiteChecker:
    def __init__(self, func):
        print('> Класс SiteChecker метод __init__ успешный запуск')
        self.func = func

    def __call__(self):
        print('> Проверка перед запуском', self.func.__name__)
        self.func()
        print('> Проверка безопасного выключения')


@SiteChecker
def site():
    print('Усердная работа сайта')

    
if __name__ == '__main__':
    print('>> Сайт запущен')
    site()
    print('>> Сайт выключен')
```
### Результат.

![Меню](https://github.com/ssselfish/SoftwareEngineering/blob/Тема_10/лаб10/5.png)

### Вывод
написан декоратор для проверки запуска сайта

## Самостоятельная работа №10
#1

```python
import time

def time_it(func):
    def wrapper(*args, **kwargs):
        start_time = time.time()
        result = func(*args, **kwargs)
        end_time = time.time()
        print(f"Время выполнения функции {func.__name__}: {end_time - start_time:.4f} секунд")
        return result
    return wrapper

@time_it
def fibonacci():
    fib = [0, 1]
    for i in range(2, 200):
        fib.append(fib[i - 1] + fib[i - 2])
    for i in range(2, 200):
        print(fib[i], end=' ')

if __name__ == '__main__':
    fibonacci()
```
### Результат.

![Меню](https://github.com/ssselfish/SoftwareEngineering/blob/Тема_10/сам10/1.png)

### Вывод
подсчет времения выполнения функции, которая считает числа fibonacci.

#2

```python
def read_file(filename):
    try:
        with open(filename, 'r', encoding='utf-8') as file:
            content = file.read()
            if not content:
                raise ValueError("Тут пусто")
            print("Содержимое файла:")
            print(content)
    except ValueError as e:
        print(e)
    except FileNotFoundError:
        print("Не найдено")

read_file("empty_file.txt")
read_file("non_empty_file.txt")
```
### Результат.

![Меню](https://github.com/ssselfish/SoftwareEngineering/blob/Тема_10/сам10/2.png)

### Вывод
реализовывается функция, которая выводит содержимое файла, при этом обрабатывает ошибку
  
#3

```python
def sum_numbers(number):
  try:
    result = 2 + int(number)
    print(f"Результат: {result}")
  except ValueError:
    print("Неподходящий тип данных. Ожидалось число.")

sum_numbers(5)
sum_numbers("hello")
sum_numbers(3.14)
```
### Результат.

![Меню](https://github.com/ssselfish/SoftwareEngineering/blob/Тема_10/сам10/3.png)

### Вывод
реализована функция сложения чисел, которая также отлавливает ошибку неподходящего типа данных
  
#4

```python
class Decorator:
    def __init__(self, times):
        self.times = times

    def __call__(self, func):
        def wrapper(*args, **kwargs):
            for i in range(self.times):
                print(f"Выполнение {i + 1} из {self.times}")
                result = func(*args, **kwargs)
            return result  
        return wrapper

@Decorator(times=4)
def square_number(number):
    
    return number * number

@Decorator(times=6)
def print_message(message):
    
    print(message)

print("Запуск функции square_number:")
result = square_number(5)
print(f"Результат: {result}")

print("\nЗапуск функции print_message:")
print_message("Hello, world!")
```
### Результат.

![Меню](https://github.com/ssselfish/SoftwareEngineering/blob/Тема_10/сам10/4.png)

### Вывод 
создается свой класс декоратор, который имеет две функции, далее при помощи декоратора запускаются функции столько, сколько обозначено в параметре
  
#5

```python
class InvalidAgeError(Exception):
    def __init__(self, message="Возраст должен быть не менее 18 лет"):
        super().__init__(message)

def check_age(age):
    if age < 18:
        raise InvalidAgeError()
    print(f"Доступ разрешен. Вам {age} лет.")

def get_user_age():
    while True:
        try:
            age = int(input("Введите ваш возраст: "))
            check_age(age)
            return age
        except ValueError:
            print("Введите число!")
        except InvalidAgeError as e:
            print(e)

if __name__ == "__main__":
    try:
        age = get_user_age()
        print(f"Ваш возраст: {age}")
    except InvalidAgeError as e:
        print(e)
```
### Результат.

![Меню](https://github.com/ssselfish/SoftwareEngineering/blob/Тема_10/сам10/5.png)
### Вывод 
программа проверяет возраст, и если введенное значение не число, то выводится ошибка

## Общий вывод 
были изучены декораторы и работа с исключениями 
